#ifndef WEB_UI_HTML_H
#define WEB_UI_HTML_H

/*
 * WebUI_HTML.h - High-Speed Minified Embedded Telemetry & Remote
 * Single-page application optimized for fast UART transfer (~4KB)
 *
 * Poll cadence: the page re-arms itself with setTimeout(poll, N) only AFTER the previous
 * /api/status request finishes, so the real update period is N + the request time.
 * Measured request time is ~320 ms, because serving it takes several AT-command round
 * trips to the ESP8266 over the blocking 115200 UART. N was 800 ms (about 1.1 s between
 * updates) and is now 300 ms (about 0.6 s).
 * Do not shorten N much further: the requests cannot overlap by design, so polling faster
 * than the link can serve only queues work and makes updates LESS regular, not faster.
 *
 * Keep comments OUT of the HTML string itself - every byte is transferred to the browser.
 */

static const char WEB_UI_HTML[] =
"<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\">"
"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no\">"
"<link rel=\"icon\" href=\"data:,\">"
"<title>DiscVU Web Remote & Telemetry</title>"
"<style>"
":root{--bg:#0d1117;--pbg:#161b22;--bdr:#30363d;--txt:#c9d1d9;--dim:#8b949e;--ac:#58a6ff;--grn:#39ff14;--ok:#7ee787;--err:#ff7b72;--warn:#d29922;--btn:#21262d}"
"*{box-sizing:border-box;margin:0;padding:0}"
"body{background:var(--bg);color:var(--txt);font-family:-apple-system,BlinkMacSystemFont,\"Segoe UI\",Roboto,sans-serif;display:flex;flex-direction:column;height:100vh;height:100dvh;overflow:hidden}"
".header{background:var(--pbg);border-bottom:1px solid var(--bdr);padding:6px 10px;display:flex;flex-wrap:wrap;justify-content:space-between;align-items:center;gap:6px;font-size:12px;font-weight:600;flex-shrink:0}"
".pills{display:flex;gap:5px;align-items:center;flex-wrap:wrap}"
".pill{background:var(--btn);padding:2px 7px;border-radius:10px;border:1px solid var(--bdr);font-size:11px;display:inline-flex;align-items:center}"
".pill.online{border-color:#2ea043;color:var(--ok)}"
".pill.carrier{border-color:var(--ac);color:var(--ac)}"
".pill.error{border-color:#da3633;color:var(--err)}"
".main{flex:1;display:flex;flex-direction:column;padding:6px 10px;gap:6px;min-height:0;overflow:hidden}"
".term-box{flex:1.2;display:flex;flex-direction:column;background:#000;border:1px solid var(--bdr);border-radius:5px;min-height:110px;overflow:hidden}"
".term-hdr{background:var(--pbg);border-bottom:1px solid var(--bdr);padding:4px 8px;display:flex;justify-content:space-between;align-items:center;font-size:11px;font-weight:700;color:var(--dim)}"
".b-mini{padding:2px 6px;font-size:10px;border-radius:3px;background:var(--btn);color:var(--txt);border:1px solid var(--bdr);cursor:pointer}"
".b-mini.active{background:#1f6feb;border-color:var(--ac);color:#fff}"
".term-body{flex:1;padding:6px 8px;font-family:Consolas,monospace;font-size:12px;overflow-y:scroll;white-space:pre-wrap;word-break:break-all;color:var(--grn);line-height:1.35}"
".stats-box{flex:1;display:flex;flex-direction:column;background:var(--pbg);border:1px solid var(--bdr);border-radius:5px;min-height:130px;overflow-y:auto}"
".stats-top{background:var(--btn);padding:5px 8px;font-size:11px;font-weight:700;color:#ffd166;border-bottom:1px solid var(--bdr);display:flex;justify-content:space-between}"
".stats-grid{display:grid;grid-template-columns:1fr 1fr;gap:3px 10px;padding:6px 8px;font-size:11.5px;font-family:Consolas,monospace}"
".s-row{display:flex;justify-content:space-between;border-bottom:1px dashed #21262d;padding:1px 0}"
".s-lbl{color:var(--dim)}.s-val{font-weight:700;color:#fff}.s-val.ok{color:var(--ok)}.s-val.warn{color:var(--warn)}.s-val.err{color:var(--err)}.s-val.hl{color:var(--ac)}"
".meta{background:var(--bg);border:1px solid var(--bdr);border-radius:4px;margin:4px 8px 6px 8px;padding:4px 6px;font-size:11px;font-family:Consolas,monospace}"
".meta-t{color:#e3b341;font-weight:700}.meta-d{color:var(--ok)}"
".ctrls{background:var(--pbg);border-top:1px solid var(--bdr);padding:6px 10px;display:flex;flex-direction:column;gap:5px;flex-shrink:0}"
".c-row{display:flex;gap:5px;align-items:center}"
".grow{flex:1}"
"input[type=\"text\"]{background:var(--bg);border:1px solid var(--bdr);color:var(--txt);padding:5px 8px;border-radius:4px;width:100%;font-size:12px;outline:none}"
"button{background:#2ea043;color:#fff;border:1px solid rgba(0,0,0,.2);padding:5px 10px;border-radius:4px;font-weight:600;font-size:11px;cursor:pointer}"
"button.sec{background:#30363d}button.danger{background:#da3633}button.active{background:#1f6feb;border-color:var(--ac)}"
"@media(max-width:600px){.stats-grid{grid-template-columns:1fr}}"
"</style></head><body>"
"<div class=\"header\">"
"  <div class=\"pills\">"
"    <div class=\"pill online\" id=\"ip\">IP: Connecting...</div>"
"    <div class=\"pill\" id=\"cpu\">CPU: --%</div>"
"    <div class=\"pill carrier\" id=\"carrier\">[NO CARRIER]</div>"
"  </div>"
"  <div class=\"pills\">"
"    <div class=\"pill\" id=\"baud\">Baud: 1200</div>"
"    <div class=\"pill\" id=\"err\">Err: +0.00%</div>"
"    <div class=\"pill\" id=\"snr\">SNR: -- dB</div>"
"  </div>"
"</div>"
"<div class=\"main\">"
"  <div class=\"term-box\">"
"    <div class=\"term-hdr\">"
"      <span>REAL-TIME FSK TERMINAL STREAM</span>"
"      <div>"
"        <button class=\"b-mini active\" id=\"b-scroll\" onclick=\"toggleScroll()\">AUTO-SCROLL: ON</button>"
"        <button class=\"b-mini\" onclick=\"clearTerm()\">CLEAR LOG</button>"
"      </div>"
"    </div>"
"    <div class=\"term-body\" id=\"term\">Waiting for incoming FSK audio carrier...</div>"
"  </div>"
"  <div class=\"stats-box\">"
"    <div class=\"stats-top\"><span id=\"side-tc\">SIDE A | TIMECODE: 00:00:00 (0s)</span><span id=\"mode-badge\" style=\"color:var(--ac)\">MODE: DCT AUTO</span></div>"
"    <div class=\"stats-grid\">"
"      <div class=\"s-row\"><span class=\"s-lbl\">Total Records:</span><span class=\"s-val\" id=\"st-tot\">0</span></div>"
"      <div class=\"s-row\"><span class=\"s-lbl\">Speed Error:</span><span class=\"s-val ok\" id=\"st-err\">+0.00%</span></div>"
"      <div class=\"s-row\"><span class=\"s-lbl\">Data Errors:</span><span class=\"s-val ok\" id=\"st-derrs\">0</span></div>"
"      <div class=\"s-row\"><span class=\"s-lbl\">Measured Baud:</span><span class=\"s-val\" id=\"st-mbaud\">1200.0</span></div>"
"      <div class=\"s-row\"><span class=\"s-lbl\">Side A Recs:</span><span class=\"s-val\" id=\"st-sa\">0 (0.0%)</span></div>"
"      <div class=\"s-row\"><span class=\"s-lbl\">Signal SNR:</span><span class=\"s-val hl\" id=\"st-snr\">-- dB</span></div>"
"      <div class=\"s-row\"><span class=\"s-lbl\">Side B Recs:</span><span class=\"s-val\" id=\"st-sb\">0 (0.0%)</span></div>"
"      <div class=\"s-row\"><span class=\"s-lbl\">Carrier State:</span><span class=\"s-val\" id=\"st-car\">Unlocked</span></div>"
"      <div class=\"s-row\"><span class=\"s-lbl\">Format Errs:</span><span class=\"s-val\" id=\"st-ferrs\">L=0 N=0</span></div>"
"      <div class=\"s-row\"><span class=\"s-lbl\">Total Stops:</span><span class=\"s-val\" id=\"st-stops\">0</span></div>"
"      <div class=\"s-row\"><span class=\"s-lbl\">Wow & Flutter:</span><span class=\"s-val ok\" id=\"st-wf\">0.00% [OK]</span></div>"
"      <div class=\"s-row\"><span class=\"s-lbl\">W/F Peak:</span><span class=\"s-val\" id=\"st-wfpeak\">0.00%</span></div>"
"    </div>"
"    <div class=\"meta\">"
"      <div class=\"meta-t\" id=\"m-file\">FILE: Standby</div>"
"      <div class=\"meta-d\" id=\"m-det\">HASH: --- | DUR: 00:00 | --- kbps</div>"
"    </div>"
"  </div>"
"</div>"
"<div class=\"ctrls\">"
"  <div class=\"c-row\">"
"    <input type=\"text\" id=\"tx-in\" placeholder=\"Type text to transmit over FSK audio DAC...\">"
"    <button onclick=\"sendTx()\">TX SEND</button>"
"  </div>"
"  <div class=\"c-row\">"
"    <button id=\"b-spk\" class=\"sec grow\" onclick=\"toggleMode('spk_mon')\">AUDIO MON</button>"
"    <button id=\"b-test\" class=\"sec grow\" onclick=\"toggleMode('test_mode')\">TX ENCODER</button>"
"    <button id=\"b-dct\" class=\"sec grow\" onclick=\"toggleMode('dct_mode')\">DCT MODE</button>"
"    <button class=\"sec grow\" onclick=\"cmd('macro','TEST')\">SEND TEST</button>"
"    <button class=\"danger\" onclick=\"cmd('reset',0)\">RESET STATS</button>"
"  </div>"
"  <div class=\"c-row\">"
"    <button class=\"sec\" onclick=\"setB(300)\">300 Bd</button>"
"    <button class=\"sec\" onclick=\"setB(600)\">600 Bd</button>"
"    <button class=\"sec\" onclick=\"setB(1200)\">1200 Bd</button>"
"    <div class=\"grow\" style=\"text-align:right;font-size:11px;color:var(--dim)\" id=\"ver\">DiscVU v0.7.0</div>"
"  </div>"
"</div>"
"<script>"
"let autoScroll=true,stateTest=false,stateDct=false,stateSpk=false,updating=false;"
"function toggleScroll(){autoScroll=!autoScroll;const b=document.getElementById('b-scroll');b.innerText=autoScroll?'AUTO-SCROLL: ON':'AUTO-SCROLL: OFF';b.classList.toggle('active',autoScroll);if(autoScroll)scrollTerm();}"
"function scrollTerm(){const t=document.getElementById('term');t.scrollTop=t.scrollHeight;}"
"function clearTerm(){document.getElementById('term').innerText='';}"
"async function poll(){"
"  if(updating)return;updating=true;"
"  try{"
"    const res=await fetch('/api/status');"
"    if(res.ok){"
"      const d=await res.json();"
"      document.getElementById('ip').innerText='IP: '+(d.param_ip||'---');"
"      document.getElementById('cpu').innerText='CPU: '+(d.param_cpu!==undefined?d.param_cpu:0)+'%';"
"      document.getElementById('baud').innerText='Baud: '+(d.param_baud||1200);"
"      const ev=d.param_speed_error||0;"
"      const ep=document.getElementById('err');"
"      ep.innerText='Err: '+(ev>=0?'+':'')+ev.toFixed(2)+'%';"
"      ep.className=Math.abs(ev)>1.5?'pill error':'pill online';"
"      const cp=document.getElementById('carrier');"
"      if(d.carrier){cp.innerText='[CARRIER: '+Math.round(d.param_measured_baud||1200)+' Bd]';cp.className='pill online';}"
"      else{cp.innerText='[NO CARRIER]';cp.className='pill carrier';}"
"      document.getElementById('snr').innerText='SNR: '+(d.snr?d.snr.toFixed(1):'--')+' dB';"
"      if(d.param_version)document.getElementById('ver').innerText='DiscVU '+d.param_version;"
"      if(d.rx_text!==undefined){"
"        const tm=document.getElementById('term');"
"        if(tm.innerText!==d.rx_text){tm.innerText=d.rx_text||'Waiting for incoming FSK carrier...';if(autoScroll)setTimeout(scrollTerm,10);}"
"      }"
"      document.getElementById('side-tc').innerText='SIDE '+(d.side||'A')+' | TIMECODE: '+(d.timecode||'00:00:00')+' ('+(d.time_seconds||0)+'s)';"
"      document.getElementById('mode-badge').innerText='MODE: '+(d.mode||'DCT AUTO').toUpperCase();"
"      document.getElementById('st-tot').innerText=d.total_recs||0;"
"      const spe=document.getElementById('st-err');spe.innerText=(ev>=0?'+':'')+ev.toFixed(2)+'%';spe.className=Math.abs(ev)>1.5?'s-val err':'s-val ok';"
"      const dte=document.getElementById('st-derrs');dte.innerText=d.data_errors||0;dte.className=(d.data_errors>0)?'s-val err':'s-val ok';"
"      document.getElementById('st-mbaud').innerText=(d.param_measured_baud||0).toFixed(1);"
"      document.getElementById('st-sa').innerText=(d.side_a_count||0)+' ('+(d.side_a_err||0).toFixed(1)+'%)';"
"      document.getElementById('st-sb').innerText=(d.side_b_count||0)+' ('+(d.side_b_err||0).toFixed(1)+'%)';"
"      document.getElementById('st-snr').innerText=(d.snr||0).toFixed(1)+' dB';"
"      document.getElementById('st-car').innerText=d.carrier?'Locked':'Unlocked';"
"      document.getElementById('st-ferrs').innerText='L='+(d.len_errors||0)+' N='+(d.num_errors||0);"
"      document.getElementById('st-stops').innerText=d.stops||0;"
"      const wfv=d.param_wf_pct||0,wfe=document.getElementById('st-wf');"
"      wfe.innerText=wfv.toFixed(2)+'% '+(wfv>0.4?'[HIGH]':wfv>0.2?'[WARN]':'[OK]');"
"      wfe.className=wfv>0.4?'s-val err':wfv>0.2?'s-val warn':'s-val ok';"
"      document.getElementById('st-wfpeak').innerText=(d.param_wf_peak||0).toFixed(2)+'%';"
"      if(d.has_meta&&d.meta_file){"
"        document.getElementById('m-file').innerText='FILE: '+d.meta_file;"
"        document.getElementById('m-det').innerText='HASH: '+(d.meta_hash||'---')+' | DUR: '+(d.meta_dur||'00:00')+' | '+(d.meta_bitrate||0)+' kbps';"
"      }else if(d.now_playing&&d.now_playing.length>0&&d.now_playing!=='Stopped'){"
"        document.getElementById('m-file').innerText='NOW PLAYING: '+d.now_playing;"
"        document.getElementById('m-det').innerText='CLIENT SYNCED • SIDE '+(d.side||'A');"
"      }else if(d.last_record&&d.last_record.length>0&&!d.last_record.includes('NOCARRIER')){"
"        document.getElementById('m-file').innerText='LAST RECORD: '+d.last_record;"
"        document.getElementById('m-det').innerText='Waiting for track metadata...';"
"      }else{"
"        document.getElementById('m-file').innerText='NOW PLAYING: Standby';"
"        document.getElementById('m-det').innerText='Waiting for carrier/track info...';"
"      }"
"      setBtn('b-spk',d.param_spk);setBtn('b-test',d.param_test);setBtn('b-dct',d.param_dct);"
"      stateSpk=d.param_spk;stateTest=d.param_test;stateDct=d.param_dct;"
"    }"
"  }catch(e){console.error(e);}"
"  finally{updating=false;setTimeout(poll,300);}"
"}"
"async function sendTx(){"
"  const inp=document.getElementById('tx-in'),val=inp.value;"
"  if(!val)return;"
"  try{await fetch('/api/tx',{method:'POST',headers:{'Content-Type':'text/plain'},body:val});inp.value='';}catch(e){}"
"}"
"async function cmd(c,v){"
"  try{await fetch('/api/cmd',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({cmd:c,val:v})});setTimeout(poll,100);}catch(e){}"
"}"
"function setB(b){cmd('baud',b);}"
"function toggleMode(m){"
"  let nv=0;"
"  if(m==='spk_mon')nv=stateSpk?0:1;"
"  else if(m==='test_mode')nv=stateTest?0:1;"
"  else if(m==='dct_mode')nv=stateDct?0:1;"
"  cmd(m,nv);"
"}"
"function setBtn(id,act){"
"  const b=document.getElementById(id);if(!b)return;"
"  b.classList.toggle('active',!!act);b.classList.toggle('sec',!act);"
"}"
"document.getElementById('tx-in').addEventListener('keydown',e=>{if(e.key==='Enter')sendTx();});"
"poll();"
"</script></body></html>\n";

#endif // WEB_UI_HTML_H
